---
exclude_paths:
  - .github/
  - venv/
skip_list:
  # We should start writing changelogs at some point
  - galaxy[no-changelog]
  # We allow Ansible 2.14 for EL9
  - meta-runtime[unsupported-version]
