---
galaxy_info:
  author: RaBe IT-Reaktion
  description: Install certbot, configure certificate renewal and deploy certificates to another host.
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-certbot/issues
  license: AGPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - foreman
    - letsencrypt
    - certbot
    - container
    - podman
    - docker
    - rsync
dependencies: []
